services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: BookingDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: 
      context: .
      dockerfile: BookingApp.API/Dockerfile
    ports:
      - "7140:80"
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__PostgresDb=Host=postgres;Port=5432;Database=BookingDb;Username=postgres;Password=password123123

  frontend:
    build:
      context: ./BookingApp.Angular
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api

volumes:
  postgres_data: