// <auto-generated />
using System;
using BookingApp.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingApp.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250528095648_SeededAdditionalFields")]
    partial class SeededAdditionalFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingApp.Domain.Entities.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "AC"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Wi-fi"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Gaming Console"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Coffee"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Audio Station"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Karaoke"
                        });
                });

            modelBuilder.Entity("BookingApp.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BookingApp.Domain.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 10,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 20,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 20,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 1,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 2,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 5,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 10,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 1,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 2,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 5,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 14,
                            Capacity = 1,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 15,
                            Capacity = 2,
                            TypeId = 2
                        });
                });

            modelBuilder.Entity("BookingApp.Domain.Entities.Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A vibrant shared area perfect for freelancers or small teams who enjoy a collaborative atmosphere. Choose any available desk and get to work with flexibility and ease.",
                            Name = "Open Space"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Designed for productive meetings, workshops, or client presentations. Equipped with screens, whiteboards, and comfortable seating to keep your sessions running smoothly.",
                            Name = "Private Rooms"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Ideal for focused work, video calls, or small team huddles. These fully enclosed rooms offer privacy and come in a variety of sizes to fit your needs.",
                            Name = "Meeting Rooms"
                        });
                });

            modelBuilder.Entity("BookingApp.Domain.Entities.TypeAmenity", b =>
                {
                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<int>("AmenityId")
                        .HasColumnType("int");

                    b.HasKey("TypeId", "AmenityId");

                    b.HasIndex("AmenityId");

                    b.ToTable("TypeAmenties");

                    b.HasData(
                        new
                        {
                            TypeId = 1,
                            AmenityId = 1
                        },
                        new
                        {
                            TypeId = 1,
                            AmenityId = 2
                        },
                        new
                        {
                            TypeId = 1,
                            AmenityId = 3
                        },
                        new
                        {
                            TypeId = 1,
                            AmenityId = 4
                        },
                        new
                        {
                            TypeId = 2,
                            AmenityId = 1
                        },
                        new
                        {
                            TypeId = 2,
                            AmenityId = 2
                        },
                        new
                        {
                            TypeId = 2,
                            AmenityId = 5
                        },
                        new
                        {
                            TypeId = 3,
                            AmenityId = 1
                        },
                        new
                        {
                            TypeId = 3,
                            AmenityId = 2
                        },
                        new
                        {
                            TypeId = 3,
                            AmenityId = 5
                        },
                        new
                        {
                            TypeId = 3,
                            AmenityId = 6
                        });
                });

            modelBuilder.Entity("BookingApp.Domain.Entities.Booking", b =>
                {
                    b.HasOne("BookingApp.Domain.Entities.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("BookingApp.Domain.Entities.Room", b =>
                {
                    b.HasOne("BookingApp.Domain.Entities.Type", "Type")
                        .WithMany("Rooms")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("BookingApp.Domain.Entities.TypeAmenity", b =>
                {
                    b.HasOne("BookingApp.Domain.Entities.Amenity", "Amenity")
                        .WithMany("TypeAmenities")
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingApp.Domain.Entities.Type", "Type")
                        .WithMany("TypeAmenities")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("BookingApp.Domain.Entities.Amenity", b =>
                {
                    b.Navigation("TypeAmenities");
                });

            modelBuilder.Entity("BookingApp.Domain.Entities.Room", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("BookingApp.Domain.Entities.Type", b =>
                {
                    b.Navigation("Rooms");

                    b.Navigation("TypeAmenities");
                });
#pragma warning restore 612, 618
        }
    }
}
