// <auto-generated />
using System;
using BookingApp.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingApp.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250611093448_CoworkingAdded")]
    partial class CoworkingAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingApp.Domain.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            HouseNumber = "12",
                            Street = "Khreshchatyk St"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            HouseNumber = "7",
                            Street = "Velyka Vasylkivska St"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            HouseNumber = "5",
                            Street = "Svobody Avenue"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            HouseNumber = "14",
                            Street = "Halytska St"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 3,
                            HouseNumber = "4",
                            Street = "Troitska Square"
                        });
                });

            modelBuilder.Entity("BookingApp.Domain.Entities.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "AC"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Wi-fi"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Gaming Console"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Coffee"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Audio Station"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Karaoke"
                        });
                });

            modelBuilder.Entity("BookingApp.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BookingApp.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kyiv"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Lviv"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dnipro"
                        });
                });

            modelBuilder.Entity("BookingApp.Domain.Entities.Coworking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Coworkings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            Description = "A modern coworking space in the heart of Kyiv with high-speed internet and flexible workstations.",
                            Name = "UrbanSpace Kyiv"
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 2,
                            Description = "Creative hub for freelancers and startups, located near central metro lines in Kyiv.",
                            Name = "HiveHub"
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 3,
                            Description = "Industrial-style coworking in Lviv offering 24/7 access and cozy meeting rooms.",
                            Name = "Lviv Loft"
                        },
                        new
                        {
                            Id = 4,
                            AddressId = 4,
                            Description = "Coworking in historic Lviv with a focus on tech startups and events.",
                            Name = "Galician Space"
                        },
                        new
                        {
                            Id = 5,
                            AddressId = 5,
                            Description = "Spacious coworking center in Dnipro with private offices and open desks.",
                            Name = "Dnipro Works"
                        });
                });

            modelBuilder.Entity("BookingApp.Domain.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoworkingId")
                        .HasColumnType("int");

                    b.Property<int?>("RoomCapacityId")
                        .HasColumnType("int");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoworkingId");

                    b.HasIndex("RoomCapacityId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoworkingId = 1,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            CoworkingId = 1,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            CoworkingId = 1,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            CoworkingId = 1,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            CoworkingId = 1,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 6,
                            CoworkingId = 1,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 7,
                            CoworkingId = 1,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 8,
                            CoworkingId = 1,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 9,
                            CoworkingId = 1,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 10,
                            CoworkingId = 1,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 11,
                            CoworkingId = 1,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 12,
                            CoworkingId = 1,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 13,
                            CoworkingId = 1,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 14,
                            CoworkingId = 1,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 15,
                            CoworkingId = 1,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 16,
                            CoworkingId = 1,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 17,
                            CoworkingId = 1,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 18,
                            CoworkingId = 1,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 19,
                            CoworkingId = 1,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 20,
                            CoworkingId = 1,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 21,
                            CoworkingId = 2,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 22,
                            CoworkingId = 2,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 23,
                            CoworkingId = 2,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 24,
                            CoworkingId = 2,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 25,
                            CoworkingId = 2,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 26,
                            CoworkingId = 2,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 27,
                            CoworkingId = 2,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 28,
                            CoworkingId = 2,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 29,
                            CoworkingId = 2,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 30,
                            CoworkingId = 2,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 31,
                            CoworkingId = 2,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 32,
                            CoworkingId = 2,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 33,
                            CoworkingId = 2,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 34,
                            CoworkingId = 2,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 35,
                            CoworkingId = 2,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 36,
                            CoworkingId = 2,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 37,
                            CoworkingId = 2,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 38,
                            CoworkingId = 2,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 39,
                            CoworkingId = 2,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 40,
                            CoworkingId = 3,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 41,
                            CoworkingId = 3,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 42,
                            CoworkingId = 3,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 43,
                            CoworkingId = 3,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 44,
                            CoworkingId = 3,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 45,
                            CoworkingId = 3,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 46,
                            CoworkingId = 3,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 47,
                            CoworkingId = 3,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 48,
                            CoworkingId = 3,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 49,
                            CoworkingId = 3,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 50,
                            CoworkingId = 3,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 51,
                            CoworkingId = 3,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 52,
                            CoworkingId = 3,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 53,
                            CoworkingId = 3,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 54,
                            CoworkingId = 3,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 55,
                            CoworkingId = 3,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 56,
                            CoworkingId = 3,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 57,
                            CoworkingId = 3,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 58,
                            CoworkingId = 3,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 59,
                            CoworkingId = 3,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 60,
                            CoworkingId = 4,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 61,
                            CoworkingId = 4,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 62,
                            CoworkingId = 4,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 63,
                            CoworkingId = 4,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 64,
                            CoworkingId = 4,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 65,
                            CoworkingId = 4,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 66,
                            CoworkingId = 4,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 67,
                            CoworkingId = 4,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 68,
                            CoworkingId = 4,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 69,
                            CoworkingId = 4,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 70,
                            CoworkingId = 4,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 71,
                            CoworkingId = 4,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 72,
                            CoworkingId = 4,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 73,
                            CoworkingId = 4,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 74,
                            CoworkingId = 4,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 75,
                            CoworkingId = 4,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 76,
                            CoworkingId = 4,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 77,
                            CoworkingId = 4,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 78,
                            CoworkingId = 4,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 79,
                            CoworkingId = 4,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 80,
                            CoworkingId = 4,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 81,
                            CoworkingId = 4,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 82,
                            CoworkingId = 4,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 83,
                            CoworkingId = 5,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 84,
                            CoworkingId = 5,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 85,
                            CoworkingId = 5,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 86,
                            CoworkingId = 5,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 87,
                            CoworkingId = 5,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 88,
                            CoworkingId = 5,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 89,
                            CoworkingId = 5,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 90,
                            CoworkingId = 5,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 91,
                            CoworkingId = 5,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 92,
                            CoworkingId = 5,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 93,
                            CoworkingId = 5,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 94,
                            CoworkingId = 5,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 95,
                            CoworkingId = 5,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 96,
                            CoworkingId = 5,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 97,
                            CoworkingId = 5,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 98,
                            CoworkingId = 5,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 99,
                            CoworkingId = 5,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 100,
                            CoworkingId = 5,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 101,
                            CoworkingId = 1,
                            RoomCapacityId = 4,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 102,
                            CoworkingId = 1,
                            RoomCapacityId = 5,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 103,
                            CoworkingId = 1,
                            RoomCapacityId = 5,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 104,
                            CoworkingId = 1,
                            RoomCapacityId = 1,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 105,
                            CoworkingId = 1,
                            RoomCapacityId = 2,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 106,
                            CoworkingId = 1,
                            RoomCapacityId = 3,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 107,
                            CoworkingId = 1,
                            RoomCapacityId = 4,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 108,
                            CoworkingId = 1,
                            RoomCapacityId = 1,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 109,
                            CoworkingId = 1,
                            RoomCapacityId = 2,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 110,
                            CoworkingId = 1,
                            RoomCapacityId = 3,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 111,
                            CoworkingId = 1,
                            RoomCapacityId = 1,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 112,
                            CoworkingId = 1,
                            RoomCapacityId = 2,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 113,
                            CoworkingId = 2,
                            RoomCapacityId = 4,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 114,
                            CoworkingId = 2,
                            RoomCapacityId = 5,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 115,
                            CoworkingId = 2,
                            RoomCapacityId = 5,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 116,
                            CoworkingId = 2,
                            RoomCapacityId = 1,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 117,
                            CoworkingId = 2,
                            RoomCapacityId = 2,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 118,
                            CoworkingId = 2,
                            RoomCapacityId = 3,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 119,
                            CoworkingId = 2,
                            RoomCapacityId = 4,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 120,
                            CoworkingId = 2,
                            RoomCapacityId = 1,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 121,
                            CoworkingId = 2,
                            RoomCapacityId = 2,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 122,
                            CoworkingId = 2,
                            RoomCapacityId = 3,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 123,
                            CoworkingId = 2,
                            RoomCapacityId = 1,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 124,
                            CoworkingId = 2,
                            RoomCapacityId = 2,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 125,
                            CoworkingId = 3,
                            RoomCapacityId = 4,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 126,
                            CoworkingId = 3,
                            RoomCapacityId = 5,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 127,
                            CoworkingId = 3,
                            RoomCapacityId = 5,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 128,
                            CoworkingId = 3,
                            RoomCapacityId = 1,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 129,
                            CoworkingId = 3,
                            RoomCapacityId = 2,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 130,
                            CoworkingId = 3,
                            RoomCapacityId = 3,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 131,
                            CoworkingId = 3,
                            RoomCapacityId = 4,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 132,
                            CoworkingId = 3,
                            RoomCapacityId = 1,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 133,
                            CoworkingId = 3,
                            RoomCapacityId = 2,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 134,
                            CoworkingId = 3,
                            RoomCapacityId = 3,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 135,
                            CoworkingId = 3,
                            RoomCapacityId = 1,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 136,
                            CoworkingId = 3,
                            RoomCapacityId = 2,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 137,
                            CoworkingId = 4,
                            RoomCapacityId = 4,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 138,
                            CoworkingId = 4,
                            RoomCapacityId = 5,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 139,
                            CoworkingId = 4,
                            RoomCapacityId = 5,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 140,
                            CoworkingId = 5,
                            RoomCapacityId = 4,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 141,
                            CoworkingId = 5,
                            RoomCapacityId = 5,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 142,
                            CoworkingId = 5,
                            RoomCapacityId = 5,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 143,
                            CoworkingId = 5,
                            RoomCapacityId = 1,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 144,
                            CoworkingId = 5,
                            RoomCapacityId = 2,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 145,
                            CoworkingId = 5,
                            RoomCapacityId = 3,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 146,
                            CoworkingId = 5,
                            RoomCapacityId = 4,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 147,
                            CoworkingId = 5,
                            RoomCapacityId = 1,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 148,
                            CoworkingId = 5,
                            RoomCapacityId = 2,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 149,
                            CoworkingId = 5,
                            RoomCapacityId = 3,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 150,
                            CoworkingId = 5,
                            RoomCapacityId = 1,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 151,
                            CoworkingId = 5,
                            RoomCapacityId = 2,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 152,
                            CoworkingId = 1,
                            RoomCapacityId = 1,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 153,
                            CoworkingId = 2,
                            RoomCapacityId = 4,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 154,
                            CoworkingId = 3,
                            RoomCapacityId = 3,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 155,
                            CoworkingId = 4,
                            RoomCapacityId = 5,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 156,
                            CoworkingId = 5,
                            RoomCapacityId = 2,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 157,
                            CoworkingId = 1,
                            RoomCapacityId = 2,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 158,
                            CoworkingId = 1,
                            RoomCapacityId = 3,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 159,
                            CoworkingId = 2,
                            RoomCapacityId = 5,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 160,
                            CoworkingId = 2,
                            RoomCapacityId = 4,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 161,
                            CoworkingId = 3,
                            RoomCapacityId = 1,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 162,
                            CoworkingId = 3,
                            RoomCapacityId = 4,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 163,
                            CoworkingId = 4,
                            RoomCapacityId = 5,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 164,
                            CoworkingId = 4,
                            RoomCapacityId = 4,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 165,
                            CoworkingId = 5,
                            RoomCapacityId = 2,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 166,
                            CoworkingId = 5,
                            RoomCapacityId = 3,
                            RoomTypeId = 2
                        });
                });

            modelBuilder.Entity("BookingApp.Domain.Entities.RoomCapacity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Capacity")
                        .IsUnique();

                    b.ToTable("RoomCapacities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 1
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 2
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 5
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 10
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 20
                        });
                });

            modelBuilder.Entity("BookingApp.Domain.Entities.RoomCapacityRoomType", b =>
                {
                    b.Property<int>("RoomCapacityId")
                        .HasColumnType("int");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.HasKey("RoomCapacityId", "RoomTypeId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("RoomCapacityRoomTypes");

                    b.HasData(
                        new
                        {
                            RoomCapacityId = 1,
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomCapacityId = 2,
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomCapacityId = 3,
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomCapacityId = 4,
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomCapacityId = 4,
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomCapacityId = 5,
                            RoomTypeId = 3
                        });
                });

            modelBuilder.Entity("BookingApp.Domain.Entities.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A vibrant shared area perfect for freelancers or small teams who enjoy a collaborative atmosphere. Choose any available desk and get to work with flexibility and ease.",
                            Type = "Open Space"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Designed for productive meetings, workshops, or client presentations. Equipped with screens, whiteboards, and comfortable seating to keep your sessions running smoothly.",
                            Type = "Private Rooms"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Ideal for focused work, video calls, or small team huddles. These fully enclosed rooms offer privacy and come in a variety of sizes to fit your needs.",
                            Type = "Meeting Rooms"
                        });
                });

            modelBuilder.Entity("BookingApp.Domain.Entities.RoomTypeAmenity", b =>
                {
                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.Property<int>("AmenityId")
                        .HasColumnType("int");

                    b.HasKey("RoomTypeId", "AmenityId");

                    b.HasIndex("AmenityId");

                    b.ToTable("RoomTypeAmenties");

                    b.HasData(
                        new
                        {
                            RoomTypeId = 1,
                            AmenityId = 1
                        },
                        new
                        {
                            RoomTypeId = 1,
                            AmenityId = 2
                        },
                        new
                        {
                            RoomTypeId = 1,
                            AmenityId = 3
                        },
                        new
                        {
                            RoomTypeId = 1,
                            AmenityId = 4
                        },
                        new
                        {
                            RoomTypeId = 2,
                            AmenityId = 1
                        },
                        new
                        {
                            RoomTypeId = 2,
                            AmenityId = 2
                        },
                        new
                        {
                            RoomTypeId = 2,
                            AmenityId = 5
                        },
                        new
                        {
                            RoomTypeId = 3,
                            AmenityId = 1
                        },
                        new
                        {
                            RoomTypeId = 3,
                            AmenityId = 2
                        },
                        new
                        {
                            RoomTypeId = 3,
                            AmenityId = 5
                        },
                        new
                        {
                            RoomTypeId = 3,
                            AmenityId = 6
                        });
                });

            modelBuilder.Entity("BookingApp.Domain.Entities.Address", b =>
                {
                    b.HasOne("BookingApp.Domain.Entities.City", null)
                        .WithMany("Addresses")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookingApp.Domain.Entities.Booking", b =>
                {
                    b.HasOne("BookingApp.Domain.Entities.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("BookingApp.Domain.Entities.Coworking", b =>
                {
                    b.HasOne("BookingApp.Domain.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("BookingApp.Domain.Entities.Room", b =>
                {
                    b.HasOne("BookingApp.Domain.Entities.Coworking", "Coworking")
                        .WithMany("Rooms")
                        .HasForeignKey("CoworkingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingApp.Domain.Entities.RoomCapacity", "RoomCapacity")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomCapacityId");

                    b.HasOne("BookingApp.Domain.Entities.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coworking");

                    b.Navigation("RoomCapacity");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("BookingApp.Domain.Entities.RoomCapacityRoomType", b =>
                {
                    b.HasOne("BookingApp.Domain.Entities.RoomCapacity", "RoomCapacity")
                        .WithMany("RoomTypes")
                        .HasForeignKey("RoomCapacityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingApp.Domain.Entities.RoomType", "RoomType")
                        .WithMany("RoomCapacities")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomCapacity");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("BookingApp.Domain.Entities.RoomTypeAmenity", b =>
                {
                    b.HasOne("BookingApp.Domain.Entities.Amenity", "Amenity")
                        .WithMany("RoomTypeAmenities")
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingApp.Domain.Entities.RoomType", "RoomType")
                        .WithMany("RoomTypeAmenities")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("BookingApp.Domain.Entities.Amenity", b =>
                {
                    b.Navigation("RoomTypeAmenities");
                });

            modelBuilder.Entity("BookingApp.Domain.Entities.City", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("BookingApp.Domain.Entities.Coworking", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("BookingApp.Domain.Entities.Room", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("BookingApp.Domain.Entities.RoomCapacity", b =>
                {
                    b.Navigation("RoomTypes");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("BookingApp.Domain.Entities.RoomType", b =>
                {
                    b.Navigation("RoomCapacities");

                    b.Navigation("RoomTypeAmenities");

                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
